import { PrismaClient, ProductType, PackagingType, ProductStatus } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Bắt đầu seed dữ liệu Products...');

  await prisma.product.deleteMany({});

  // Lấy các category và supplier ID để map
  const categories = await prisma.category.findMany();
  const suppliers = await prisma.supplier.findMany();

  // Helper để tìm category
  const findCategory = (code: string) => categories.find((c) => c.categoryCode === code)?.id;

  // Helper để tìm supplier
  const findSupplier = (code: string) => suppliers.find((s) => s.supplierCode === code)?.id;

  const products = [
    // ================================================================
    // NHÓM 1: THÀNH PHẨM - SẢN PHẨM BÁN RA (FINISHED PRODUCTS)
    // ================================================================

    // --- Kích thích sinh trưởng ---
    {
      sku: 'TP-KTSW-SIEUDAUTRAI-500ML',
      slug: 'sieu-dau-trai-500ml',
      productName: 'SIÊU ĐẬU TRÁI 500ml',
      productType: ProductType.finished_product,
      packagingType: PackagingType.bottle,
      categoryId: findCategory('TP-KICH-THICH'),
      supplierId: null, // Tự sản xuất
      unit: 'Chai',
      barcode: '8936124567801',
      weight: 0.55, // kg (bao gồm chai)
      dimensions: '7x7x20cm',
      description:
        'Kích thích ra hoa, đậu trái đều. Chứa Amino acid + Hormon tự nhiên. Dùng cho cây ăn trái, rau màu.',
      purchasePrice: 28000, // Chi phí sản xuất 1 chai
      sellingPriceRetail: 65000, // Giá bán lẻ cho nông dân
      sellingPriceWholesale: 52000, // Giá bán buôn cho đại lý
      sellingPriceVip: 48000, // Giá cho đại lý VIP
      taxRate: 5.0,
      minStockLevel: 200,
      expiryDate: new Date('2026-12-31'),
      status: ProductStatus.active,
    },
    {
      sku: 'TP-KTSW-NAVIMINO-OT-1L',
      slug: 'navi-amino-chuyen-ot-1l',
      productName: 'NAVI AMINO - Chuyên dùng cho Ớt 1L',
      productType: ProductType.finished_product,
      packagingType: PackagingType.bottle,
      categoryId: findCategory('TP-KICH-THICH'),
      supplierId: null,
      unit: 'Chai',
      barcode: '8936124567802',
      weight: 1.1,
      dimensions: '9x9x25cm',
      description: 'Amino acid đặc trị cho cây ớt. Chống rụng hoa, tăng tỷ lệ đậu trái, cứng cây.',
      purchasePrice: 52000,
      sellingPriceRetail: 125000,
      sellingPriceWholesale: 105000,
      sellingPriceVip: 98000,
      taxRate: 5.0,
      minStockLevel: 150,
      expiryDate: new Date('2026-10-31'),
      status: ProductStatus.active,
    },

    // --- Dinh dưỡng & Phân bón lá ---
    {
      sku: 'TP-DDLA-BONLONTRAI-17-17-17-1KG',
      slug: 'bon-lon-trai-17-17-17-1kg',
      productName: 'BÓN LỚN TRÁI 17-17-17 (NPK) 1kg',
      productType: ProductType.finished_product,
      packagingType: PackagingType.bag,
      categoryId: findCategory('TP-DINH-DUONG'),
      supplierId: null,
      unit: 'Gói',
      barcode: '8936124567803',
      weight: 1.05,
      dimensions: '15x20x5cm',
      description:
        'Phân bón lá NPK cân đối 17-17-17. Giúp trái phát triển đều, tăng năng suất. Hòa tan hoàn toàn.',
      purchasePrice: 38000,
      sellingPriceRetail: 85000,
      sellingPriceWholesale: 72000,
      sellingPriceVip: 68000,
      taxRate: 5.0,
      minStockLevel: 300,
      expiryDate: new Date('2027-06-30'),
      status: ProductStatus.active,
    },
    {
      sku: 'TP-DDLA-CANXI-BO-OT-500ML',
      slug: 'canxi-bo-ot-thai-500ml',
      productName: 'CANXI-BO ỚT THÁI 500ml',
      productType: ProductType.finished_product,
      packagingType: PackagingType.bottle,
      categoryId: findCategory('TP-DINH-DUONG'),
      supplierId: null,
      unit: 'Chai',
      barcode: '8936124567804',
      weight: 0.58,
      dimensions: '7x7x20cm',
      description:
        'Bổ sung Canxi + Bo cho cây ớt. Chống đọt non, chống nứt trái, tăng độ cứng quả.',
      purchasePrice: 26000,
      sellingPriceRetail: 62000,
      sellingPriceWholesale: 50000,
      sellingPriceVip: 47000,
      taxRate: 5.0,
      minStockLevel: 180,
      expiryDate: new Date('2026-09-30'),
      status: ProductStatus.active,
    },
    {
      sku: 'TP-DDLA-AMINO-ATONIC-1L',
      slug: 'amino-atonic-1l',
      productName: 'AMINO ATONIC 1L',
      productType: ProductType.finished_product,
      packagingType: PackagingType.bottle,
      categoryId: findCategory('TP-DINH-DUONG'),
      supplierId: null,
      unit: 'Chai',
      barcode: '8936124567805',
      weight: 1.15,
      dimensions: '9x9x26cm',
      description:
        'Amino acid tổng hợp giúp cây phục hồi sau stress (hạn, úng, sâu bệnh). Kích thích sinh trưởng mạnh.',
      purchasePrice: 55000,
      sellingPriceRetail: 135000,
      sellingPriceWholesale: 115000,
      sellingPriceVip: 108000,
      taxRate: 5.0,
      minStockLevel: 120,
      expiryDate: new Date('2026-11-30'),
      status: ProductStatus.active,
    },

    // --- Vi sinh & Trừ bệnh ---
    {
      sku: 'TP-VS-TRICHODERMA-500G',
      slug: 'trichoderma-500g',
      productName: 'TRICHODERMA - Nấm đối kháng 500g',
      productType: ProductType.finished_product,
      packagingType: PackagingType.bag,
      categoryId: findCategory('TP-VI-SINH'),
      supplierId: null,
      unit: 'Gói',
      barcode: '8936124567806',
      weight: 0.52,
      dimensions: '12x18x4cm',
      description:
        'Chế phẩm vi sinh Trichoderma 10^8 bào tử/g. Phòng trừ nấm bệnh thán thư, héo xanh, thối rễ.',
      purchasePrice: 42000,
      sellingPriceRetail: 95000,
      sellingPriceWholesale: 80000,
      sellingPriceVip: 75000,
      taxRate: 5.0,
      minStockLevel: 100,
      expiryDate: new Date('2025-12-31'), // Vi sinh hết hạn nhanh hơn
      status: ProductStatus.active,
    },

    // --- Chuyên dùng cho cây ăn trái ---
    {
      sku: 'TP-AT-DOCTOR-MANGO-SET',
      slug: 'doctor-mango-bo-3-chai',
      productName: 'DOCTOR MANGO - Bộ 3 chai (Xoài)',
      productType: ProductType.finished_product,
      packagingType: PackagingType.box,
      categoryId: findCategory('TP-CAY-AN-TRAI'),
      supplierId: null,
      unit: 'Bộ',
      barcode: '8936124567807',
      weight: 1.8,
      dimensions: '25x20x10cm',
      description:
        'Bộ 3 sản phẩm chuyên cho xoài: 1) Ra đọt, 2) Kích hoa, 3) Lớn trái. Đủ chu trình chăm sóc.',
      purchasePrice: 135000,
      sellingPriceRetail: 320000,
      sellingPriceWholesale: 280000,
      sellingPriceVip: 265000,
      taxRate: 5.0,
      minStockLevel: 50,
      expiryDate: new Date('2026-08-31'),
      status: ProductStatus.active,
    },
    {
      sku: 'TP-AT-CHONGRUNG-MACCA-500ML',
      slug: 'chong-rung-mac-ca-500ml',
      productName: 'CHỐNG RỤNG MẮC CA 500ml',
      productType: ProductType.finished_product,
      packagingType: PackagingType.bottle,
      categoryId: findCategory('TP-CAY-AN-TRAI'),
      supplierId: null,
      unit: 'Chai',
      barcode: '8936124567808',
      weight: 0.56,
      dimensions: '7x7x20cm',
      description:
        'Chuyên trị rụng hoa, rụng trái non cho cây Mắc ca. Chứa Kali + Bo + Hormon sinh trưởng.',
      purchasePrice: 48000,
      sellingPriceRetail: 115000,
      sellingPriceWholesale: 98000,
      sellingPriceVip: 92000,
      taxRate: 5.0,
      minStockLevel: 80,
      expiryDate: new Date('2026-07-31'),
      status: ProductStatus.active,
    },

    // --- Chuyên dùng cho Rau màu & Hoa ---
    {
      sku: 'TP-RAU-AMINCHO-RAUMAU-1L',
      slug: 'acid-amin-cho-rau-mau-1l',
      productName: 'ACID AMIN CHO RAU MÀU 1L',
      productType: ProductType.finished_product,
      packagingType: PackagingType.bottle,
      categoryId: findCategory('TP-RAU-MAU'),
      supplierId: null,
      unit: 'Chai',
      barcode: '8936124567809',
      weight: 1.12,
      dimensions: '9x9x25cm',
      description:
        'Amino acid đặc chế cho rau ăn lá, rau củ. Tăng trọng nhanh, giảm độc hại, xanh tự nhiên.',
      purchasePrice: 48000,
      sellingPriceRetail: 118000,
      sellingPriceWholesale: 100000,
      sellingPriceVip: 94000,
      taxRate: 5.0,
      minStockLevel: 140,
      expiryDate: new Date('2026-10-31'),
      status: ProductStatus.active,
    },

    // --- Chuyên dùng cho Cây công nghiệp ---
    {
      sku: 'TP-CN-DOCTOR-TIEU-1L',
      slug: 'doctor-tieu-1l',
      productName: 'DOCTOR TIÊU 1L',
      productType: ProductType.finished_product,
      packagingType: PackagingType.bottle,
      categoryId: findCategory('TP-CAY-CN'),
      supplierId: null,
      unit: 'Chai',
      barcode: '8936124567810',
      weight: 1.14,
      dimensions: '9x9x26cm',
      description: 'Chuyên cho cây tiêu. Giúp cây đâm chồi khỏe, chống héo rũ, tăng năng suất hạt.',
      purchasePrice: 58000,
      sellingPriceRetail: 140000,
      sellingPriceWholesale: 120000,
      sellingPriceVip: 112000,
      taxRate: 5.0,
      minStockLevel: 90,
      expiryDate: new Date('2026-12-31'),
      status: ProductStatus.active,
    },

    // ================================================================
    // NHÓM 2: NGUYÊN LIỆU - HÓA CHẤT SẢN XUẤT (RAW MATERIALS)
    // ================================================================

    // --- Hóa chất Đa lượng ---
    {
      sku: 'NL-DL-UREA-46N-25KG',
      slug: 'urea-46n-25kg',
      productName: 'Urea 46%N - Bao 25kg',
      productType: ProductType.raw_material,
      packagingType: PackagingType.bag,
      categoryId: findCategory('NL-DA-LUONG'),
      supplierId: findSupplier('NCC-DAM-CAMAU'),
      unit: 'Bao',
      barcode: null,
      weight: 25.0,
      dimensions: '50x80x15cm',
      description: 'Đạm Urea hạt đục 46%N - Cà Mau. Nguồn Nitơ chính để pha chế phân bón.',
      purchasePrice: 285000,
      sellingPriceRetail: null, // Nguyên liệu không bán lẻ
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 5.0,
      minStockLevel: 100, // 2.5 tấn
      expiryDate: null, // Hóa chất không hết hạn nhanh
      status: ProductStatus.active,
    },
    {
      sku: 'NL-DL-MAP-12-61-25KG',
      slug: 'map-12-61-25kg',
      productName: 'MAP (12-61-0) - Bao 25kg',
      productType: ProductType.raw_material,
      packagingType: PackagingType.bag,
      categoryId: findCategory('NL-DA-LUONG'),
      supplierId: findSupplier('NCC-HOACHAT-DUCGIANG'),
      unit: 'Bao',
      barcode: null,
      weight: 25.0,
      dimensions: '50x80x15cm',
      description: 'Mono Ammonium Phosphate - Nguồn Lân và Đạm cao. Dùng để pha NPK hòa tan.',
      purchasePrice: 420000,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 5.0,
      minStockLevel: 80,
      expiryDate: null,
      status: ProductStatus.active,
    },
    {
      sku: 'NL-DL-KALI-NITRAT-25KG',
      slug: 'kno3-kali-nitrat-25kg',
      productName: 'Kali Nitrat (KNO3) - Bao 25kg',
      productType: ProductType.raw_material,
      packagingType: PackagingType.bag,
      categoryId: findCategory('NL-DA-LUONG'),
      supplierId: findSupplier('NCC-HAIFA-ISRAEL'),
      unit: 'Bao',
      barcode: null,
      weight: 25.0,
      dimensions: '50x80x15cm',
      description: 'Kali Nitrat Haifa Israel - 13-0-46. Nguồn Kali + Nitơ cao cấp cho phân lá.',
      purchasePrice: 680000,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 5.0,
      minStockLevel: 50,
      expiryDate: null,
      status: ProductStatus.active,
    },

    // --- Hóa chất Vi lượng ---
    {
      sku: 'NL-VL-BORAX-1KG',
      slug: 'borax-bo-1kg',
      productName: 'Borax (Bo) 99% - Gói 1kg',
      productType: ProductType.raw_material,
      packagingType: PackagingType.bag,
      categoryId: findCategory('NL-VI-LUONG'),
      supplierId: findSupplier('NCC-XNK-VINACHEM'),
      unit: 'Gói',
      barcode: null,
      weight: 1.05,
      dimensions: '15x20x5cm',
      description: 'Borax tinh khiết 99%. Nguồn Bo để pha chế phân vi lượng, chống rụng trái.',
      purchasePrice: 45000,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 5.0,
      minStockLevel: 200,
      expiryDate: null,
      status: ProductStatus.active,
    },
    {
      sku: 'NL-VL-CHELATE-ZN-EDTA-1KG',
      slug: 'kem-kem-kep-zinc-edta-1kg',
      productName: 'Zinc EDTA (Kẽm kelat) - Gói 1kg',
      productType: ProductType.raw_material,
      packagingType: PackagingType.bag,
      categoryId: findCategory('NL-VI-LUONG'),
      supplierId: findSupplier('NCC-XNK-VINACHEM'),
      unit: 'Gói',
      barcode: null,
      weight: 1.02,
      dimensions: '15x20x5cm',
      description: 'Kẽm chelat EDTA 15%. Hấp thu cao, dùng cho phân bón lá chống vàng lá.',
      purchasePrice: 120000,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 5.0,
      minStockLevel: 150,
      expiryDate: null,
      status: ProductStatus.active,
    },

    // --- Nguyên liệu Hữu cơ & Sinh học ---
    {
      sku: 'NL-HC-AMINO-THUY-PHAN-20L',
      slug: 'amino-thuy-phan-long-20l',
      productName: 'Amino Acid thủy phân lỏng - Can 20L',
      productType: ProductType.raw_material,
      packagingType: PackagingType.other,
      categoryId: findCategory('NL-HUU-CO'),
      supplierId: findSupplier('NCC-AMINO-FRANCE'),
      unit: 'Can',
      barcode: null,
      weight: 22.0,
      dimensions: '30x30x40cm',
      description: 'Amino acid nguồn gốc động vật thủy phân enzyme. Hàm lượng 40%. Nhập khẩu Pháp.',
      purchasePrice: 1850000,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 5.0,
      minStockLevel: 20,
      expiryDate: new Date('2026-06-30'), // Nguyên liệu sinh học có hạn
      status: ProductStatus.active,
    },
    {
      sku: 'NL-HC-HUMIC-BOT-25KG',
      slug: 'humic-acid-bot-25kg',
      productName: 'Humic Acid bột 85% - Bao 25kg',
      productType: ProductType.raw_material,
      packagingType: PackagingType.bag,
      categoryId: findCategory('NL-HUU-CO'),
      supplierId: findSupplier('NCC-XNK-VINACHEM'),
      unit: 'Bao',
      barcode: null,
      weight: 25.0,
      dimensions: '50x80x15cm',
      description: 'Humic acid chiết từ than bùn. Cải tạo đất, tăng hấp thu dinh dưỡng.',
      purchasePrice: 520000,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 5.0,
      minStockLevel: 40,
      expiryDate: null,
      status: ProductStatus.active,
    },

    // --- Phụ gia & Dung môi ---
    {
      sku: 'NL-PG-SILICON-BAMDDINH-5L',
      slug: 'chat-bam-dinh-silicon-5l',
      productName: 'Chất bám dính Silicon - Can 5L',
      productType: ProductType.raw_material,
      packagingType: PackagingType.other,
      categoryId: findCategory('NL-PHU-GIA'),
      supplierId: findSupplier('NCC-XNK-VINACHEM'),
      unit: 'Can',
      barcode: null,
      weight: 5.5,
      dimensions: '20x20x30cm',
      description: 'Chất bám dính silicon giúp phân bón bám lá lâu hơn, không rửa trôi.',
      purchasePrice: 285000,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 5.0,
      minStockLevel: 30,
      expiryDate: null,
      status: ProductStatus.active,
    },

    // ================================================================
    // NHÓM 3: BAO BÌ - VẬT LIỆU ĐÓNG GÓI (PACKAGING)
    // ================================================================

    // --- Chai & Can nhựa ---
    {
      sku: 'BB-CHAI-HDPE-500ML',
      slug: 'chai-nhua-hdpe-500ml',
      productName: 'Chai nhựa HDPE 500ml (trắng)',
      productType: ProductType.packaging,
      packagingType: PackagingType.bottle,
      categoryId: findCategory('BB-CHAI-CAN'),
      supplierId: findSupplier('NCC-NHUA-DUYTAN'),
      unit: 'Cái',
      barcode: null,
      weight: 0.035,
      dimensions: '7x7x20cm',
      description: 'Chai nhựa HDPE thực phẩm, nắp vặn kín. Dùng đóng sản phẩm dạng lỏng 500ml.',
      purchasePrice: 1800,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 10.0,
      minStockLevel: 5000,
      expiryDate: null,
      status: ProductStatus.active,
    },
    {
      sku: 'BB-CHAI-HDPE-1L',
      slug: 'chai-nhua-hdpe-1l',
      productName: 'Chai nhựa HDPE 1 Lít (trắng)',
      productType: ProductType.packaging,
      packagingType: PackagingType.bottle,
      categoryId: findCategory('BB-CHAI-CAN'),
      supplierId: findSupplier('NCC-NHUA-DUYTAN'),
      unit: 'Cái',
      barcode: null,
      weight: 0.055,
      dimensions: '9x9x26cm',
      description: 'Chai nhựa HDPE 1 lít, nắp vặn kín. Đóng sản phẩm dạng lỏng.',
      purchasePrice: 2500,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 10.0,
      minStockLevel: 3000,
      expiryDate: null,
      status: ProductStatus.active,
    },
    {
      sku: 'BB-CAN-NHUA-5L',
      slug: 'can-nhua-5l',
      productName: 'Can nhựa HDPE 5 Lít',
      productType: ProductType.packaging,
      packagingType: PackagingType.bottle,
      categoryId: findCategory('BB-CHAI-CAN'),
      supplierId: findSupplier('NCC-NHUA-DUYTAN'),
      unit: 'Cái',
      barcode: null,
      weight: 0.18,
      dimensions: '18x18x30cm',
      description: 'Can nhựa 5L có quai xách. Dùng đóng sản phẩm dạng lỏng số lượng lớn.',
      purchasePrice: 9500,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 10.0,
      minStockLevel: 500,
      expiryDate: null,
      status: ProductStatus.active,
    },

    // --- Bao bì màng ghép ---
    {
      sku: 'BB-MG-TUI-NHOM-1KG',
      slug: 'tui-mang-ghep-1kg',
      productName: 'Túi màng ghép 1kg (in 2 mặt)',
      productType: ProductType.packaging,
      packagingType: PackagingType.bag,
      categoryId: findCategory('BB-MANG-GHEP'),
      supplierId: findSupplier('NCC-IN-LIKSIN'),
      unit: 'Cái',
      barcode: null,
      weight: 0.015,
      dimensions: '15x22cm (phẳng)',
      description: 'Túi màng ghép phức hợp 3 lớp, in offset 2 mặt. Dùng đóng phân bón dạng bột.',
      purchasePrice: 2200,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 10.0,
      minStockLevel: 3000,
      expiryDate: null,
      status: ProductStatus.active,
    },

    // --- Tem, Nhãn, Decal ---
    {
      sku: 'BB-TEM-DECAL-500ML',
      slug: 'tem-nhan-chai-500ml',
      productName: 'Tem decal chai 500ml (màu)',
      productType: ProductType.packaging,
      packagingType: PackagingType.label,
      categoryId: findCategory('BB-TEM-NHAN'),
      supplierId: findSupplier('NCC-IN-LIKSIN'),
      unit: 'Tờ',
      barcode: null,
      weight: 0.002,
      dimensions: '12x7cm',
      description: 'Nhãn decal dán chai 500ml. In offset màu 4/0. Chống nước.',
      purchasePrice: 450,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 10.0,
      minStockLevel: 10000,
      expiryDate: null,
      status: ProductStatus.active,
    },
    {
      sku: 'BB-TEM-HDSD-MATSAU',
      slug: 'tem-huong-dan-su-dung',
      productName: 'Tem HDSD mặt sau (trắng đen)',
      productType: ProductType.packaging,
      packagingType: PackagingType.label,
      categoryId: findCategory('BB-TEM-NHAN'),
      supplierId: findSupplier('NCC-IN-LIKSIN'),
      unit: 'Tờ',
      barcode: null,
      weight: 0.001,
      dimensions: '10x15cm',
      description: 'Tem hướng dẫn sử dụng dán mặt sau chai/túi. In 1 màu đen.',
      purchasePrice: 250,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 10.0,
      minStockLevel: 15000,
      expiryDate: null,
      status: ProductStatus.active,
    },

    // --- Thùng Carton & Đóng gói ngoài ---
    {
      sku: 'BB-CARTON-20CHAI-500ML',
      slug: 'thung-carton-20-chai-500ml',
      productName: 'Thùng carton 20 chai 500ml',
      productType: ProductType.packaging,
      packagingType: PackagingType.box,
      categoryId: findCategory('BB-NGOAI'),
      supplierId: findSupplier('NCC-BAOBI-TANTHANH'),
      unit: 'Cái',
      barcode: null,
      weight: 0.35,
      dimensions: '40x30x25cm',
      description: 'Thùng carton 3 lớp, in Offset logo công ty. Chứa vừa 20 chai 500ml xếp đứng.',
      purchasePrice: 8500,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 10.0,
      minStockLevel: 500,
      expiryDate: null,
      status: ProductStatus.active,
    },
    {
      sku: 'BB-CARTON-12CHAI-1L',
      slug: 'thung-carton-12-chai-1l',
      productName: 'Thùng carton 12 chai 1L',
      productType: ProductType.packaging,
      packagingType: PackagingType.box,
      categoryId: findCategory('BB-NGOAI'),
      supplierId: findSupplier('NCC-BAOBI-TANTHANH'),
      unit: 'Cái',
      barcode: null,
      weight: 0.42,
      dimensions: '45x35x30cm',
      description: 'Thùng carton 3 lớp, chứa 12 chai 1L. In logo & thông tin công ty.',
      purchasePrice: 9800,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 10.0,
      minStockLevel: 400,
      expiryDate: null,
      status: ProductStatus.active,
    },
    {
      sku: 'BB-BANGKEO-OPP-50MM',
      slug: 'bang-keo-dan-thung-opp-50mm',
      productName: 'Băng keo dán thùng OPP 50mm x 100m',
      productType: ProductType.packaging,
      packagingType: PackagingType.other,
      categoryId: findCategory('BB-NGOAI'),
      supplierId: findSupplier('NCC-BAOBI-TANTHANH'),
      unit: 'Cuộn',
      barcode: null,
      weight: 0.52,
      dimensions: '10x10x5cm',
      description: 'Băng keo trong OPP dán thùng carton. In logo công ty.',
      purchasePrice: 18000,
      sellingPriceRetail: null,
      sellingPriceWholesale: null,
      sellingPriceVip: null,
      taxRate: 10.0,
      minStockLevel: 200,
      expiryDate: null,
      status: ProductStatus.active,
    },
  ];

  // Insert products
  for (const product of products) {
    await prisma.product.upsert({
      where: { sku: product.sku },
      update: product,
      create: product,
    });
  }

  console.log(`✅ Đã seed xong ${products.length} sản phẩm!`);
  console.log(`   - Thành phẩm: 10 sản phẩm`);
  console.log(`   - Nguyên liệu: 9 loại hóa chất`);
  console.log(`   - Bao bì: 10 loại (chai, nhãn, thùng...)`);
}

main()
  .catch((e) => {
    console.error('❌ Lỗi khi seed products:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
